### ISSUE TITLE
Baseurl Hardcoded

### ISSUE THREAD

**Issue by AlexandreKilian** [steffenbrem/JsonApiBundle#25]
Hello,

Since i'm not using domain.tld/api/resource but rather api.domain.tld/resource, I'm running into a problem with the following:
in https://github.com/steffenbrem/JsonApiBundle/blob/master/EventListener/Serializer/JsonEventSubscriber.php#L67 , the baseurl is hard coded as /api with no options to change it, thus making all the generated urls invalid. Wouldn't it be a  better approach to use the symfony router to generate these urls dynamically, thus giving the opportunity of a custom URL structure?

**Comment by koemeet** [comment]
I am not so sure about using the url generator from Symfony2, since JsonAPI spec is pretty clear on how the URLs should be structured. I would like to keep this automatic to ease configuration. Maybe in the future I could make this optional. 

I will work on making a configuration to specify an absolute url prefix.

**Comment by koemeet** [comment]
@AlexandreKilian Right now I have implemented a way to resolve the base uri for the generated links. This should be enough to cover most cases, if not please tell me.
